name: CI Workflows

on:
  push:
    branches:
      master
  pull_request:

permissions:
  contents: write

jobs:

  initial_checks:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      display: true
      coverage: codecov
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-0
          - libegl1-mesa
          - libhdf5-dev

  deploy-examples:
    needs: initial_checks
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy examples to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: examples 

